ci:
  autofix_commit_msg: "style(pre-commit): autofix"

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
