name: regression_test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget unzip

      - name: Download data
        run: |
          ./script/download_data.sh

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p build
          cd build
          cmake ..
          make -j
          cd ..

      - name: Run
        run: |
          ./script/execute_regression_test.sh
